# Task: Cuisine Classification
Objective: Develop a machine learning model to
classify restaurants based on their cuisines.
Steps:
Preprocess the dataset by handling missing values
and encoding categorical variables.
Split the data into training and testing sets.
Select a classification algorithm (e.g., logistic
regression, random forest) and train it on the
training data.
Evaluate the model's performance using
appropriate classification metrics (e.g., accuracy,
precision, recall) on the testing data.
Analyze the model's performance across different
cuisines and identify any challeng or biases.
T

In [410]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [411]:
import warnings
warnings.filterwarnings("ignore")

In [412]:
df=pd.read_csv("C:\\Users\\Mpatt\\OneDrive\\Desktop\\AssignmentDATASet\\Dataset.csv")
print(df)

      Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208         ��stanbul
9547        5908749              Ceviz A��ac۱           208         ��stanbul
9548        5915807                     Huqqa           208         ��stanbul
9549        5916112               A���k Kahve           208         ��stanbul
9550        5927402  Walter's Coffee Roastery           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]

In [413]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [414]:
# Handle missing values
df.fillna(method='ffill', inplace=True)
df= df.replace("�", "",  regex=True)
print(df)

      Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208           stanbul
9547        5908749                Ceviz Aac۱           208           stanbul
9548        5915807                     Huqqa           208           stanbul
9549        5916112                  Ak Kahve           208           stanbul
9550        5927402  Walter's Coffee Roastery           208           stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke Karamustafa Paa Mahallesi, R۱ht۱m Cadd...
9547  Kouyolu Mahallesi, Muhittin st_nda Caddesi, No...
9548  Kuru_eme Mahallesi, Muallim Naci Caddesi, No 5...
9549  Kuru_eme Mahallesi, Muallim Naci Caddesi, No 6...
9550  Cafeaa Mahallesi, Bademalt۱ Sokak, No 21/B, Ka...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                     Karak_y
9547                                     Kouyolu
9548                                    Kuru_eme
9549                                    Kuru_eme
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                   Karak_y, stanbul   28.977392
9547                                   Kouyolu, stanbul   29.041297
9548                                  Kuru_eme, stanbul   29.034640
9549                                  Kuru_eme, stanbul   29.036019
9550                                      Moda, stanbul   29.026016

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)
1     14.553708                          Japanese  ...  Botswana Pula(P)
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)
...         ...                               ...  ...               ...
9546  41.022793                           Turkish  ...  Turkish Lira(TL)
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)
9550  40.984776                              Cafe  ...  Turkish Lira(TL)

     Has Table booking Has Online delivery Is delivering now  \
0                  Yes                  No                No
1                  Yes                  No                No
2                  Yes                  No                No
3                   No                  No                No
4                  Yes                  No                No
...                ...                 ...               ...
9546                No                  No                No
9547                No                  No                No
9548                No                  No                No
9549                No                  No                No
9550                No                  No                No

     Switch to order menu Price range  Aggregate rating  Rating color  \
0                      No           3               4.8    Dark Green
1                      No           3               4.5    Dark Green
2                      No           4               4.4         Green
3                      No           4               4.9    Dark Green
4                      No           4               4.8    Dark Green
...                   ...         ...               ...           ...
9546                   No           3               4.1         Green
9547                   No           3               4.2         Green
9548                   No           4               3.7        Yellow
9549                   No           4               4.0         Green
9550                   No           2               4.0         Green

     Rating text Votes
0      Excellent   314
1      Excellent   591
2      Very Good   270
3      Excellent   365
4      Excellent   229
...          ...   ...
9546   Very Good   788
9547   Very Good  1034
9548        Good   661
9549   Very Good   901
9550   Very Good   591

[9551 rows x 21 columns]

In [415]:
  # Data Preprocessing
df=df.drop(['Restaurant ID','Country Code','City','Address', 'Locality','Locality Verbose','Longitude','Latitude','Currency','Has Table booking','Has Online delivery','Is delivering now','Switch to order menu','Price range','Aggregate rating','Rating color','Votes'], axis=1)
print(df.columns)

Index(['Restaurant Name', 'Cuisines', 'Average Cost for two', 'Rating text'], dtype='object')

In [416]:
df.shape
df.info

<bound method DataFrame.info of                Restaurant Name                          Cuisines  \
0             Le Petit Souffle        French, Japanese, Desserts
1             Izakaya Kikufuji                          Japanese
2       Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian
3                         Ooma                   Japanese, Sushi
4                  Sambo Kojin                  Japanese, Korean
...                        ...                               ...
9546               Naml۱ Gurme                           Turkish
9547                Ceviz Aac۱   World Cuisine, Patisserie, Cafe
9548                     Huqqa            Italian, World Cuisine
9549                  Ak Kahve                   Restaurant Cafe
9550  Walter's Coffee Roastery                              Cafe

      Average Cost for two Rating text
0                     1100   Excellent
1                     1200   Excellent
2                     4000   Very Good
3                     1500   Excellent
4                     1500   Excellent
...                    ...         ...
9546                    80   Very Good
9547                   105   Very Good
9548                   170        Good
9549                   120   Very Good
9550                    55   Very Good

[9551 rows x 4 columns]>

In [417]:
df.describe()

       Average Cost for two
count           9551.000000
mean            1199.210763
std            16121.183073
min                0.000000
25%              250.000000
50%              400.000000
75%              700.000000
max           800000.000000

In [418]:
df.isnull().sum()

Restaurant Name         0
Cuisines                0
Average Cost for two    0
Rating text             0
dtype: int64

In [419]:
# Checking missing vaalues for each col
missing_values = df.isna().sum() 
missing_values_column = df['Restaurant Name'].isna().sum() 
missing_values_column = df['Cuisines'].isna().sum() 
missing_values_column = df['Rating text'].isna().sum()
missing_values_column = df['Average Cost for two'].isna().sum()

In [420]:
df_cleaned = df.dropna() 
df_cleaned = df.dropna(subset=['Restaurant Name']) 
df_cleaned = df.dropna(subset=['Cuisines']) 
df_cleaned = df.dropna(subset=['Rating text'])
df_cleaned = df.dropna(subset=['Average Cost for two'])

In [421]:
df.describe(include="all")

        Restaurant Name      Cuisines  Average Cost for two Rating text
count              9551          9551           9551.000000        9551
unique             7446          1825                   NaN           6
top     Cafe Coffee Day  North Indian                   NaN     Average
freq                 83           936                   NaN        3737
mean                NaN           NaN           1199.210763         NaN
std                 NaN           NaN          16121.183073         NaN
min                 NaN           NaN              0.000000         NaN
25%                 NaN           NaN            250.000000         NaN
50%                 NaN           NaN            400.000000         NaN
75%                 NaN           NaN            700.000000         NaN
max                 NaN           NaN         800000.000000         NaN

In [422]:
# Converting Categorical data to NUmerical
from sklearn.preprocessing import LabelEncoder 

label_encoder = LabelEncoder() 
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name']) 
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])
df

      Restaurant Name  Cuisines  Average Cost for two Rating text
0                3748       920                  1100   Excellent
1                3172      1111                  1200   Excellent
2                2897      1671                  4000   Very Good
3                4707      1126                  1500   Excellent
4                5523      1122                  1500   Excellent
...               ...       ...                   ...         ...
9546             4443      1813                    80   Very Good
9547             1311      1824                   105   Very Good
9548             3069      1110                   170        Good
9549              210      1657                   120   Very Good
9550             7240       331                    55   Very Good

[9551 rows x 4 columns]

In [423]:
rating_mapping = {
    "Excellent": 5,
    "Very Good": 4,
    "Good":3 ,
    "Not rated":0,
    "Average":2,
    "Poor":1
    }
df["Rating Numerical"] = df["Rating text"].map(rating_mapping)

print(df)

      Restaurant Name  Cuisines  Average Cost for two Rating text  \
0                3748       920                  1100   Excellent
1                3172      1111                  1200   Excellent
2                2897      1671                  4000   Very Good
3                4707      1126                  1500   Excellent
4                5523      1122                  1500   Excellent
...               ...       ...                   ...         ...
9546             4443      1813                    80   Very Good
9547             1311      1824                   105   Very Good
9548             3069      1110                   170        Good
9549              210      1657                   120   Very Good
9550             7240       331                    55   Very Good

      Rating Numerical
0                    5
1                    5
2                    4
3                    5
4                    5
...                ...
9546                 4
9547                 4
9548                 3
9549                 4
9550                 4

[9551 rows x 5 columns]

In [424]:
df.isnull().sum()

Restaurant Name         0
Cuisines                0
Average Cost for two    0
Rating text             0
Rating Numerical        0
dtype: int64

# Building Model

In [425]:
'''x= df[['Restaurant Name', 'Rating Numerical']] 
y = df['Cuisines']

from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(x)
x= scaler.transform(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=10)'''

"x= df[['Restaurant Name', 'Rating Numerical']] \ny = df['Cuisines']\n\nfrom sklearn.preprocessing import StandardScaler\nscaler= StandardScaler()\nscaler.fit(x)\nx= scaler.transform(x)\n\nfrom sklearn.model_selection import train_test_split\nx_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=10)"

In [426]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

# Encode 'Restaurant Name' (categorical feature) as numerical
df['Restaurant Name Encoded'] = LabelEncoder().fit_transform(df['Restaurant Name'])

# Encode target variable 'Cuisines'
y = LabelEncoder().fit_transform(df['Cuisines'])

# Define features (using numeric columns only)
x = df[['Restaurant Name Encoded', 'Rating Numerical']]

# Standardize numerical features
scaler = StandardScaler()
x = scaler.fit_transform(x)

# Split dataset into training and testing sets (30% test size)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=10)

# Random Forest

In [427]:
# Train the model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=42)
model.fit(x_train, y_train)

#print(X_train)
# Predict
y_pred = model.predict(x_test)
print(y_pred)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R² Score: {r2}")

[1227.57666667  943.98        899.07       ... 1034.37        686.78
  938.23      ]
Mean Squared Error: 243199.4296328044
R² Score: 0.06664638587921401

# DecisionTreeClassifier

In [428]:
# predicting using Decision Tree Classifier.
from sklearn.tree import DecisionTreeClassifier

model_DT = DecisionTreeClassifier(random_state=10,
                                   criterion="gini")

# fit the model on data and predict the values
model_DT.fit(x_train,y_train)      # fit is the function that is used for training the data
y_pred = model_DT.predict(x_test) # Validation Data
#print(Y_pred)
print(y_pred)

[1287 1015  630 ... 1031  177  891]

In [429]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
'''cfm=confusion_matrix(y_test,y_pred)
print(cfm)
 
print("modelDT report: ")
print(model_DT(y_test,y_pred))'''
 
acc=accuracy_score(y_test,y_pred)
print("Accuracy of the model: ",acc)

Accuracy of the model:  0.19050942079553385

# Logistic Regression

In [430]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression(multi_class="multinomial")
#train the model object
classifier.fit(x_train,y_train)     
y_pred = classifier.predict(x_test)
print(y_pred)

[1306 1031 1306 ...  331 1306  331]

In [431]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(y_test,y_pred))
 
acc=accuracy_score(y_test,y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         5
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         3
          30       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         8
          58       0.00      0.00      0.00        10
          61       0.00      0.00      0.00         1
          62       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         2
          71       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         1
          84       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         2
          95       0.00      0.00      0.00         1
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         3
         100       0.00      0.00      0.00         1
         101       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         2
         106       0.00      0.00      0.00         1
         109       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         1
         115       0.00      0.00      0.00         5
         121       0.00      0.00      0.00         3
         123       0.00      0.00      0.00         1
         124       0.00      0.00      0.00         1
         129       0.00      0.00      0.00         1
         134       0.00      0.00      0.00         1
         140       0.00      0.00      0.00         1
         151       0.00      0.00      0.00         1
         152       0.00      0.00      0.00         1
         153       0.00      0.00      0.00         1
         154       0.00      0.00      0.00         1
         155       0.00      0.00      0.00         1
         156       0.00      0.00      0.00         1
         161       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         163       0.00      0.00      0.00         1
         168       0.00      0.00      0.00         2
         169       0.00      0.00      0.00         1
         173       0.00      0.00      0.00         1
         177       0.00      0.00      0.00        65
         181       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         183       0.00      0.00      0.00         1
         184       0.00      0.00      0.00         1
         186       0.00      0.00      0.00        72
         188       0.00      0.00      0.00         1
         190       0.00      0.00      0.00         1
         191       0.00      0.00      0.00        14
         194       0.00      0.00      0.00         1
         195       0.00      0.00      0.00         1
         197       0.00      0.00      0.00         1
         201       0.00      0.00      0.00        39
         204       0.00      0.00      0.00         1
         211       0.00      0.00      0.00         4
         216       0.00      0.00      0.00         1
         221       0.00      0.00      0.00         1
         223       0.00      0.00      0.00         1
         225       0.00      0.00      0.00         1
         226       0.00      0.00      0.00         1
         230       0.00      0.00      0.00        15
         233       0.00      0.00      0.00         3
         235       0.00      0.00      0.00         1
         236       0.00      0.00      0.00         1
         241       0.00      0.00      0.00         2
         243       0.00      0.00      0.00        14
         246       0.00      0.00      0.00         2
         249       0.00      0.00      0.00         6
         251       0.00      0.00      0.00         5
         255       0.00      0.00      0.00         2
         256       0.00      0.00      0.00         1
         257       0.00      0.00      0.00         3
         258       0.00      0.00      0.00         2
         259       0.00      0.00      0.00         1
         261       0.00      0.00      0.00         1
         265       0.00      0.00      0.00         1
         266       0.00      0.00      0.00         1
         268       0.00      0.00      0.00         2
         269       0.00      0.00      0.00         1
         272       0.00      0.00      0.00         1
         273       0.00      0.00      0.00         1
         274       0.00      0.00      0.00         1
         275       0.00      0.00      0.00         1
         285       0.00      0.00      0.00         2
         287       0.00      0.00      0.00         1
         288       0.00      0.00      0.00         1
         289       0.00      0.00      0.00         1
         294       0.00      0.00      0.00         4
         297       0.00      0.00      0.00         3
         300       0.00      0.00      0.00         1
         301       0.00      0.00      0.00         1
         305       0.00      0.00      0.00         1
         306       0.00      0.00      0.00         1
         307       0.00      0.00      0.00         5
         310       0.00      0.00      0.00        13
         311       0.00      0.00      0.00         2
         313       0.00      0.00      0.00         1
         321       0.00      0.00      0.00         1
         323       0.00      0.00      0.00         1
         325       0.00      0.00      0.00         1
         328       0.00      0.00      0.00         1
         331       0.02      0.09      0.04        99
         334       0.00      0.00      0.00         1
         335       0.00      0.00      0.00         1
         336       0.00      0.00      0.00         1
         342       0.00      0.00      0.00         1
         344       0.00      0.00      0.00         5
         346       0.00      0.00      0.00         2
         347       0.00      0.00      0.00         2
         352       0.00      0.00      0.00         1
         355       0.00      0.00      0.00         1
         357       0.00      0.00      0.00         1
         358       0.00      0.00      0.00         3
         363       0.00      0.00      0.00         1
         364       0.00      0.00      0.00         1
         369       0.00      0.00      0.00         1
         370       0.00      0.00      0.00         1
         371       0.00      0.00      0.00         1
         373       0.00      0.00      0.00         1
         375       0.00      0.00      0.00         1
         376       0.00      0.00      0.00         1
         378       0.00      0.00      0.00         1
         379       0.00      0.00      0.00         3
         380       0.00      0.00      0.00         1
         381       0.00      0.00      0.00         1
         383       0.00      0.00      0.00         1
         387       0.00      0.00      0.00         1
         392       0.00      0.00      0.00         1
         394       0.00      0.00      0.00         2
         397       0.00      0.00      0.00         1
         399       0.00      0.00      0.00         1
         400       0.00      0.00      0.00         3
         402       0.00      0.00      0.00         1
         403       0.00      0.00      0.00         1
         405       0.00      0.00      0.00         1
         406       0.00      0.00      0.00         1
         409       0.00      0.00      0.00         1
         412       0.00      0.00      0.00         2
         417       0.00      0.00      0.00         2
         419       0.00      0.00      0.00         1
         420       0.00      0.00      0.00         4
         421       0.00      0.00      0.00         1
         422       0.00      0.00      0.00         1
         423       0.00      0.00      0.00         1
         424       0.00      0.00      0.00         1
         426       0.00      0.00      0.00         2
         430       0.00      0.00      0.00         1
         431       0.00      0.00      0.00         1
         432       0.00      0.00      0.00         1
         435       0.00      0.00      0.00         1
         437       0.00      0.00      0.00         1
         440       0.00      0.00      0.00         1
         442       0.00      0.00      0.00         1
         444       0.00      0.00      0.00         1
         455       0.00      0.00      0.00         2
         456       0.00      0.00      0.00         1
         458       0.00      0.00      0.00         1
         464       0.00      0.00      0.00         1
         465       0.00      0.00      0.00         2
         468       0.00      0.00      0.00         1
         469       0.00      0.00      0.00         1
         471       0.00      0.00      0.00         1
         472       0.00      0.00      0.00         1
         477       0.00      0.00      0.00         1
         479       0.00      0.00      0.00         1
         482       0.00      0.00      0.00         1
         483       0.00      0.00      0.00         1
         486       0.00      0.00      0.00         1
         487       0.00      0.00      0.00         1
         491       0.00      0.00      0.00         1
         494       0.00      0.00      0.00         1
         497       0.00      0.00      0.00        99
         499       0.00      0.00      0.00         1
         500       0.00      0.00      0.00         1
         506       0.00      0.00      0.00         1
         512       0.00      0.00      0.00         3
         514       0.00      0.00      0.00         1
         515       0.00      0.00      0.00         1
         517       0.00      0.00      0.00         2
         518       0.00      0.00      0.00        37
         521       0.00      0.00      0.00         2
         522       0.00      0.00      0.00         1
         526       0.00      0.00      0.00         1
         531       0.00      0.00      0.00         1
         533       0.00      0.00      0.00         1
         540       0.00      0.00      0.00         1
         542       0.00      0.00      0.00         1
         543       0.00      0.00      0.00         1
         545       0.00      0.00      0.00         2
         546       0.00      0.00      0.00         2
         549       0.00      0.00      0.00        32
         550       0.00      0.00      0.00         1
         552       0.00      0.00      0.00         1
         553       0.00      0.00      0.00         1
         554       0.00      0.00      0.00         1
         555       0.00      0.00      0.00         2
         557       0.00      0.00      0.00         1
         560       0.00      0.00      0.00         1
         564       0.00      0.00      0.00         1
         565       0.00      0.00      0.00         1
         568       0.00      0.00      0.00         4
         570       0.00      0.00      0.00         1
         572       0.00      0.00      0.00         1
         575       0.00      0.00      0.00         2
         576       0.00      0.00      0.00         1
         579       0.00      0.00      0.00         1
         581       0.00      0.00      0.00         1
         582       0.00      0.00      0.00         7
         583       0.00      0.00      0.00         3
         585       0.00      0.00      0.00         1
         587       0.00      0.00      0.00         1
         588       0.00      0.00      0.00        16
         589       0.00      0.00      0.00         3
         590       0.00      0.00      0.00         1
         595       0.00      0.00      0.00         1
         596       0.00      0.00      0.00         1
         598       0.00      0.00      0.00         1
         600       0.00      0.00      0.00         1
         607       0.00      0.00      0.00         1
         609       0.00      0.00      0.00         1
         610       0.00      0.00      0.00         4
         614       0.00      0.00      0.00         1
         617       0.00      0.00      0.00         1
         618       0.00      0.00      0.00         1
         621       0.00      0.00      0.00         1
         622       0.00      0.00      0.00         1
         623       0.00      0.00      0.00         1
         625       0.00      0.00      0.00         8
         626       0.00      0.00      0.00         1
         628       0.00      0.00      0.00         1
         632       0.00      0.00      0.00         1
         633       0.00      0.00      0.00         1
         640       0.00      0.00      0.00         1
         642       0.00      0.00      0.00         1
         646       0.00      0.00      0.00         1
         653       0.00      0.00      0.00         1
         654       0.00      0.00      0.00         1
         658       0.00      0.00      0.00         1
         660       0.00      0.00      0.00         2
         666       0.00      0.00      0.00         1
         668       0.00      0.00      0.00         1
         669       0.00      0.00      0.00         1
         670       0.00      0.00      0.00         1
         672       0.00      0.00      0.00         1
         673       0.00      0.00      0.00         1
         675       0.00      0.00      0.00         1
         676       0.00      0.00      0.00         1
         677       0.00      0.00      0.00         1
         681       0.00      0.00      0.00         1
         684       0.00      0.00      0.00         2
         690       0.00      0.00      0.00         1
         693       0.00      0.00      0.00         2
         702       0.00      0.00      0.00         1
         705       0.00      0.00      0.00         1
         707       0.00      0.00      0.00         1
         712       0.00      0.00      0.00         1
         716       0.00      0.00      0.00         1
         719       0.00      0.00      0.00         5
         721       0.00      0.00      0.00         2
         722       0.00      0.00      0.00         3
         725       0.00      0.00      0.00         2
         727       0.00      0.00      0.00         1
         732       0.00      0.00      0.00         1
         733       0.00      0.00      0.00         1
         736       0.00      0.00      0.00         1
         737       0.00      0.00      0.00         1
         739       0.00      0.00      0.00         1
         740       0.00      0.00      0.00         1
         742       0.00      0.00      0.00         1
         749       0.00      0.00      0.00         1
         752       0.00      0.00      0.00         1
         754       0.00      0.00      0.00         1
         758       0.00      0.00      0.00        13
         760       0.00      0.00      0.00         1
         761       0.00      0.00      0.00         6
         762       0.00      0.00      0.00         1
         763       0.00      0.00      0.00         1
         765       0.00      0.00      0.00         1
         766       0.00      0.00      0.00         2
         768       0.00      0.00      0.00         2
         769       0.00      0.00      0.00         1
         770       0.00      0.00      0.00         2
         773       0.00      0.00      0.00         1
         774       0.00      0.00      0.00         9
         775       0.00      0.00      0.00         2
         778       0.00      0.00      0.00         1
         780       0.00      0.00      0.00         1
         782       0.00      0.00      0.00         1
         785       0.00      0.00      0.00         2
         787       0.00      0.00      0.00         1
         788       0.00      0.00      0.00         5
         789       0.00      0.00      0.00         1
         791       0.00      0.00      0.00         3
         792       0.00      0.00      0.00         2
         793       0.00      0.00      0.00         1
         796       0.00      0.00      0.00         1
         799       0.00      0.00      0.00         1
         803       0.00      0.00      0.00         1
         804       0.00      0.00      0.00         3
         809       0.00      0.00      0.00         1
         810       0.00      0.00      0.00         2
         812       0.00      0.00      0.00         1
         814       0.00      0.00      0.00         1
         815       0.00      0.00      0.00         1
         816       0.00      0.00      0.00         1
         818       0.00      0.00      0.00         0
         819       0.00      0.00      0.00         1
         822       0.00      0.00      0.00         1
         825       0.00      0.00      0.00         1
         826       0.00      0.00      0.00         1
         828       0.00      0.00      0.00       115
         832       0.00      0.00      0.00         1
         833       0.00      0.00      0.00         3
         834       0.00      0.00      0.00        16
         835       0.00      0.00      0.00         1
         837       0.00      0.00      0.00        19
         838       0.00      0.00      0.00         1
         840       0.00      0.00      0.00         1
         841       0.00      0.00      0.00        13
         842       0.00      0.00      0.00         1
         844       0.00      0.00      0.00         1
         849       0.00      0.00      0.00         3
         852       0.00      0.00      0.00         1
         854       0.00      0.00      0.00         1
         856       0.00      0.00      0.00         1
         858       0.00      0.00      0.00         1
         859       0.00      0.00      0.00         1
         860       0.00      0.00      0.00         1
         861       0.00      0.00      0.00         1
         862       0.00      0.00      0.00         1
         865       0.00      0.00      0.00        11
         868       0.00      0.00      0.00         1
         872       0.00      0.00      0.00         1
         874       0.00      0.00      0.00         1
         876       0.00      0.00      0.00         1
         878       0.00      0.00      0.00         2
         880       0.00      0.00      0.00         1
         882       0.00      0.00      0.00         2
         884       0.00      0.00      0.00         1
         886       0.00      0.00      0.00         4
         887       0.00      0.00      0.00         1
         890       0.00      0.00      0.00         1
         891       0.00      0.00      0.00         1
         892       0.00      0.00      0.00         1
         895       0.00      0.00      0.00        16

By comparing DecisionTreeClassifier and Logistic Regression. DecisionTreeClassifier is Performing Better as compared to Logistic Regression.